# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16XC2TP_2N1tZzSfOa1uD8fbem7Ws5KRs
"""

import pandas as pd
df = pd.read_csv('shopping_trends.csv')
df.head()

df.describe()