# -*- coding: utf-8 -*-
"""pandas_shopping_trends.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16XC2TP_2N1tZzSfOa1uD8fbem7Ws5KRs
"""

import pandas as pd
df = pd.read_csv('shopping_trends.csv')
df.head()

df.describe()

print(df.columns)

print(df['Purchase Amount (USD)'].dtype)

missing_count = df['Purchase Amount (USD)'].isna().sum()

# Display the result
print(f"Number of missing rows in 'Purchase Amount (USD)': {missing_count}")

grouped = df.groupby('Category')['Purchase Amount (USD)'].sum()
print(grouped)